apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: subatomic-cluster-admin
roleRef:
  kind: ClusterRole
  name: admin-user
subjects:
  - kind: ServiceAccount
    name: subatomic
    namespace: subatomic